# Generated by Django 5.1.5 on 2025-04-10 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='імя')),
                ('last_name', models.CharField(max_length=50, verbose_name='прізвище')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='телефон')),
                ('email', models.EmailField(max_length=100, verbose_name='емеіл')),
            ],
        ),
        migrations.CreateModel(
            name='FullOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('payment', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('total_amount', models.DecimalField(decimal_places=1, max_digits=8)),
                ('points_used', models.IntegerField(blank=True, null=True)),
                ('person', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='sweets.person')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_description', models.TextField()),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='sweets.category')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('full_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sweets.fullorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sweets.product')),
            ],
        ),
    ]
