# Generated by Django 5.1.5 on 2025-05-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweets', '0002_remove_fullorder_points_used_remove_person_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.ManyToManyField(through='sweets.ProductIngredient', to='sweets.ingredient'),
        ),
    ]
